[project]
name = "pyuploadcare-example"
version = "5.1.0"
description = "Example project for Python library for Uploadcare.com"
authors = [{ name = "Uploadcare Inc", email = "hello@uploadcare.com" }]
requires-python = ">=3.14.3,<4.0"
dependencies = [
    "Django>=4.2.28,<5",
    "django-crispy-forms>=2.1",
    "crispy-bootstrap4>=2023.1",
    "pyuploadcare>=6.2.1,<7.0.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "black>=26.3.1",
    "isort>=7.0.0",
]

[tool.black]
line-length = 100
target-version = ['py314']
exclude = '''
(
  \.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |venv
  |_build
  |buck-out
  |build
  |dist
)
'''

[tool.isort]
line_length = 100
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
src_paths = "app"
include_trailing_comma = "true"
lines_after_imports = 2
